package frontend.corbasupport.RecordManagerApp;


/**
* RecordManagerApp/RecordManager.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RecordManager.idl
* Wednesday, July 26, 2017 9:42:21 AM EDT
*/

public interface RecordManager extends RecordManagerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface RecordManager
