package frontend.corbasupport.RecordManagerApp;


/**
* RecordManagerApp/RecordManagerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RecordManager.idl
* Wednesday, July 26, 2017 9:42:21 AM EDT
*/

abstract public class RecordManagerHelper
{
  private static String  _id = "IDL:RecordManagerApp/RecordManager:1.0";

  public static void insert (org.omg.CORBA.Any a, RecordManager that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static RecordManager extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (RecordManagerHelper.id (), "RecordManager");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static RecordManager read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_RecordManagerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, RecordManager value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static RecordManager narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof RecordManager)
      return (RecordManager)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _RecordManagerStub stub = new _RecordManagerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static RecordManager unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof RecordManager)
      return (RecordManager)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _RecordManagerStub stub = new _RecordManagerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
