package frontend.corbasupport.RecordManagerApp;


/**
* RecordManagerApp/RecordManager.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RecordManager.idl
* Sunday, July 9, 2017 10:11:20 PM EDT
*/

public interface RecordManager extends RecordManagerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface RecordManager
